# Generated by Django 6.0.4 on 2026-04-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'incomplete'), ('In progress', 'in progress'), ('Complete', 'complete')], default='Incomplete', max_length=20),
        ),
    ]
